name = "Mr beast"
author = "Mr beeeeeaaaaaaassssssst"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dca478bb0b6ded88fa2d0ad088b3525fb5da5248a9b3b026d783350c8a670785"

[versions]
minecraft = "1.19.2"
quilt = "0.18.4-pre.3"
