name = "Mr beast"
author = "Mr beeeeeaaaaaaassssssst"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "776c17b6529019867a4645535068b04cf3411c0f0a9a52fbf8bc9b0b96e58d62"

[versions]
minecraft = "1.19.2"
quilt = "0.18.4-pre.3"
